- name: Install and Run nginx # name is not mandatory, this is best practice
  hosts: Anode_1
  become: yes #this will give root access
  tasks:
  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: removed
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: stopped